### ISSUE TITLE
semantic segmentation

### ISSUE THREAD

**Issue by che1007** [cilinyan/PiClick#1]
我最近也在研究clicked baesd segmentation ，發現都是做instance segmentation 。
那是否有可能藉由類似的方法來達到在同一場景下，只需點擊少量的次數即把同一類（例如：人）的部分給分割出來。

**Comment by cilinyan** [comment]
Using masks with identical semantics as ground truth as training inputs can be considered a naive approach.

**Comment by che1007** [comment]
Thanks for your reply
