### ISSUE TITLE
Evaluation without reference masks supervision

### ISSUE THREAD

**Issue by a-mos** [cilinyan/PiClick#4]
Hello, thanks for the interesting work. Currently the model [uses reference masks](https://github.com/cilinyan/PiClick/blob/main/isegm/inference/evaluation.py#L70) to select the best candidate. How to test a model based on its own estimates of mask scores?

**Comment by cilinyan** [comment]
We have added a possible implementation in the code ([scripts/evaluate_model.py](https://github.com/cilinyan/PiClick/blob/fbcac7fa5bb0d30d4a3e9fef48332a4156b9c86a/scripts/evaluate_model.py#L68) & [isegm/inference/predictors/base.py](https://github.com/cilinyan/PiClick/blob/fbcac7fa5bb0d30d4a3e9fef48332a4156b9c86a/isegm/inference/predictors/base.py#L199-L206), to minimize changes, this implementation might not be as elegant).
