### ISSUE TITLE
about the label

### ISSUE THREAD

**Issue by songbingze** [cilinyan/PiClick#7]
https://github.com/cilinyan/PiClick/blob/e472a436959f394480fda2308fd6f104efccc633/isegm/model/losses_despair.py#L552C14-L552C96

In the generated mask in SampleClick, 0 represents the background and 1 represents the foreground target. Here, all labels are set to 0. Why is this? Thanks!

**Comment by cilinyan** [comment]
This difference arises from the distinction between single-mask and multi-mask, with this particular code section being adapted from the open-source implementation of Mask2Former by mmlab. In instance segmentation tasks, when there are N different classes, it is common to use the labels 0 to N-1 to represent foreground classes, with N representing the background class. In PiClick, we treat all possible foreground classes equally, representing them with the label 0.

**Comment by songbingze** [comment]
I understand. Thank you for your reply.
